#!/usr/bin/env bash
# This is multiple choice questions, and my answers are right under the questions.
What is the OSI model?
- The OSI model is a model that characterizes the communication functions of a telecommunication system with a strong regard for their underlying internal structure and technology.

How is the OSI model organized?
- From the lowest to the highest level.
